### ISSUE TITLE
monitor login website basic_auth

### ISSUE THREAD

**Issue by cmachadox** [mbelloiseau/website-monitoring#6]
Hello how are you ? have you ever managed to monitor/validate username and password of a page/api via blackbox-exporter?

**Comment by mbelloiseau** [comment]
Hi,

Yes, I had to monitore an API with blackbox and prometheus

* prometheus.yml

```
  - job_name: "web-monitoring-http_restricted"
    metrics_path: /probe
    params:
      module: [http_2xx_restricted]
    file_sd_configs:
      - files:
        - /etc/prometheus/targets/http_restricted.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
```

* blackbox.yml

```
  http_2xx_restricted:
    prober: http
    timeout: 8s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []
      method: GET
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false 
      basic_auth:
        username: "user"
        password: "password"
```

* http_restricted.yml is just a classic target file

But I'm not sure how to manage the configuration if you've more than one host and credentials for each host
